### ISSUE TITLE
Send mail to multiple recipients

### ISSUE THREAD

**Issue by erlanger** [JanWielemaker/smtp#1]
Hi @JanWielemaker,

   First, I want to thank you for all your great work on swi prolog. In general when you do great work like that you hear of bugs and problems, but only a few times about the great work you do. So I want to thank you.

Here is a patch to allow the smtp pack to send to multiple recipients using several `RCPT TO` commands as described in the `SMTP` protocol.

The API is not changed, but if the destination address is a **list**, then multiple `RCPT TO` commands are generated and the `To:` header uses the From address (much like `Bcc:` works in MUAs).

I don't know if you are interested in this patch, so I put it here for your perusal.

```prolog
diff --git a/prolog/smtp.pl b/prolog/smtp.pl
index 67cf51b..c092885 100644
--- a/prolog/smtp.pl
+++ b/prolog/smtp.pl
@@ -265,6 +265,10 @@ close_tls(In, Out, In, Out) :- !.
 close_tls(_, _, In, Out) :-
     smtp_close(In, Out).

+rcpt_to(In, Out, To) :-
+   sock_send(Out, 'RCPT TO:<~w>\r\n', [To]),
+   read_ok(In, 250).
+
 do_send_mail_cont(In, Out, To, Goal, Lines, Options) :-
     (   option(from(From), Options)
     ->  true
@@ -273,11 +277,18 @@ do_send_mail_cont(In, Out, To, Goal, Lines, Options) :-
     auth(In, Out, From, Lines, Options),
     sock_send(Out, 'MAIL FROM:<~w>\r\n', [From]),
     read_ok(In, 250),
-    sock_send(Out, 'RCPT TO:<~w>\r\n', [To]),
-    read_ok(In, 250),
+    (   is_list(To)
+    ->  ( To1   = To,
+          ToHdr = From
+        )
+    ;   ( To1   = [To],
+          ToHdr = To
+        )
+    ),
+    maplist(rcpt_to(In, Out), To1),
     sock_send(Out, 'DATA\r\n', []),
     read_ok(In, 354),
-    format(Out, 'To: ~w\r\n', [To]),
+    format(Out, 'To: ~w\r\n', [ToHdr]),
     header_options(Out, Options),
     sock_send(Out, '\r\n', []),
     call(Goal, Out),
```

**Comment by eddiec** [comment]
This is extremely useful to be able to do.
I'd made my own changes before seeing this.

Not sure about the logic of using 'From' as the "To:" contents.  FWIW I did:

```
    ( is_list(To)
      -> atomic_list_concat(To, ',', RCPT)
      ; RCPT = To),
    format(Out, 'To: ~w\r\n', [RCPT]),

```

**Comment by JanWielemaker** [comment]
Thanks.   Forgotten ...  Pushed 1.1.0 to address this.
